[pytest]
testpaths = HP_tests_thermo
filterwarnings =
    ignore::UserWarning:MDAnalysis.*
    ignore::DeprecationWarning
markers =
    slow: takes more than a few seconds
addopts = -p no:cacheprovider